import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations);

  static List<String> languages() => ['en', 'fr', 'es', 'ja', 'hi', 'ro'];

  String get languageCode => locale.languageCode;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.languageCode] ?? '';

  String getVariableText({
    String enText = '',
    String frText = '',
    String esText = '',
    String jaText = '',
    String hiText = '',
    String roText = '',
  }) =>
      [enText, frText, esText, jaText, hiText, roText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      FFLocalizations.languages().contains(locale.languageCode);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // login
  {
    'm1lvz66b': {
      'en': 'Sign In',
      'es': 'Registrarse',
      'fr': 'S&#39;identifier',
      'hi': 'साइन इन करें',
      'ja': 'ログイン',
      'ro': 'Conectare',
    },
    'udckyewa': {
      'en': 'Sign Up',
      'es': 'Inscribirse',
      'fr': 'S&#39;inscrire',
      'hi': 'साइन अप करें',
      'ja': 'サインアップ',
      'ro': 'Inscrie-te',
    },
    '0q4l2uj1': {
      'en': 'Sign in to share more photos',
      'es': 'Inicia sesión para compartir más fotos',
      'fr': 'Connectez-vous pour partager plus de photos',
      'hi': 'अधिक फ़ोटो साझा करने के लिए साइन इन करें',
      'ja': 'サインインして他の写真を共有する',
      'ro': 'Conectați-vă pentru a partaja mai multe fotografii',
    },
    'gpfk24pf': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'ro': 'E-mail',
    },
    'peewk13o': {
      'en': 'Password',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'ro': 'Parola',
    },
    '6ca18yw1': {
      'en': 'Login',
      'es': 'Acceso',
      'fr': 'Connexion',
      'hi': 'लॉग इन करें',
      'ja': 'ログイン',
      'ro': 'Autentificare',
    },
    'vairuprg': {
      'en': 'Continue as Guest',
      'es': 'Continua como invitado',
      'fr': 'Continuer en tant qu&#39;invité',
      'hi': 'अतिथि के रूप में जारी रखें',
      'ja': 'ゲストとして続行',
      'ro': 'Continuați ca invitat',
    },
  },
  // register
  {
    '26a3g2tu': {
      'en': 'Sign In',
      'es': 'Registrarse',
      'fr': 'S&#39;identifier',
      'hi': 'साइन इन करें',
      'ja': 'ログイン',
      'ro': 'Conectare',
    },
    'vukd35yc': {
      'en': 'Sign Up',
      'es': 'Inscribirse',
      'fr': 'S&#39;inscrire',
      'hi': 'साइन अप करें',
      'ja': 'サインアップ',
      'ro': 'Inscrie-te',
    },
    '810ueda4': {
      'en': 'Get started by creating an account below.',
      'es': 'Comience creando una cuenta a continuación.',
      'fr': 'Commencez par créer un compte ci-dessous.',
      'hi': 'नीचे एक खाता बनाकर आरंभ करें।',
      'ja': '以下のアカウントを作成して始めましょう。',
      'ro': 'Începeți prin a crea un cont mai jos.',
    },
    'i45t3dhw': {
      'en': 'Email',
      'es': 'Correo electrónico',
      'fr': 'E-mail',
      'hi': 'ईमेल',
      'ja': 'Eメール',
      'ro': 'E-mail',
    },
    's2hvwgvr': {
      'en': 'Password',
      'es': 'Clave',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'ja': 'パスワード',
      'ro': 'Parola',
    },
    '7we2h5nv': {
      'en': 'Confirm Passward',
      'es': 'Confirmar contraseña',
      'fr': 'Confirmer le mot de passe',
      'hi': 'पासवार्ड की पुष्टि करें',
      'ja': 'パスワードを確認する',
      'ro': 'Confirmați Passward',
    },
    '98x3bhop': {
      'en': 'Get Started',
      'es': 'Empezar',
      'fr': 'Commencer',
      'hi': 'शुरू हो जाओ',
      'ja': 'はじめに',
      'ro': 'Incepe',
    },
    'dvxg2h1n': {
      'en': 'Continue as Guest',
      'es': 'Continua como invitado',
      'fr': 'Continuer en tant qu&#39;invité',
      'hi': 'अतिथि के रूप में जारी रखें',
      'ja': 'ゲストとして続行',
      'ro': 'Continuați ca invitat',
    },
  },
  // home
  {
    '7ftte96a': {
      'en': 'Quick Filters',
      'es': 'Filtros rápidos',
      'fr': 'Filtres rapides',
      'hi': 'त्वरित फ़िल्टर',
      'ja': 'クイックフィルター',
      'ro': 'Filtre rapide',
    },
    'j465ims6': {
      'en': 'All Images',
      'es': 'Todas las imágenes',
      'fr': 'Toutes les photos',
      'hi': 'सभी छवियां',
      'ja': 'すべての画像',
      'ro': 'Toate Imaginile',
    },
    'tscs9p3j': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
  },
  // add_image
  {
    'cpnh24yx': {
      'en': 'Add Image',
      'es': 'Añadir imagen',
      'fr': 'Ajouter une image',
      'hi': 'छवि जोड़ें',
      'ja': '画像を追加',
      'ro': 'Adauga imagine',
    },
    'becrjldq': {
      'en': 'Title',
      'es': 'Título',
      'fr': 'Titre',
      'hi': 'शीर्षक',
      'ja': '題名',
      'ro': 'Titlu',
    },
    'vhsc00r4': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'dqchwjl7': {
      'en': 'Enter post details here...',
      'es': 'Ingrese los detalles de la publicación aquí...',
      'fr': 'Entrez les détails du poste ici...',
      'hi': 'यहां पोस्ट विवरण दर्ज करें...',
      'ja': 'ここに投稿の詳細を入力してください...',
      'ro': 'Introdu aici detaliile postării...',
    },
    'zri0jsmt': {
      'en': 'Art',
      'es': 'Arte',
      'fr': 'Art',
      'hi': 'कला',
      'ja': '美術',
      'ro': 'Artă',
    },
    'uc7w4dzs': {
      'en': 'Portrait',
      'es': 'Retrato',
      'fr': 'Portrait',
      'hi': 'चित्र',
      'ja': 'ポートレート',
      'ro': 'Portret',
    },
    'zsgrqb3j': {
      'en': 'Landscape',
      'es': 'Paisaje',
      'fr': 'Paysage',
      'hi': 'परिदृश्य',
      'ja': '風景',
      'ro': 'Peisaj',
    },
    '5a9unxg1': {
      'en': 'Health',
      'es': 'Salud',
      'fr': 'Santé',
      'hi': 'स्वास्थ्य',
      'ja': '健康',
      'ro': 'Sănătate',
    },
    '24nbnkji': {
      'en': 'Fitness',
      'es': 'Aptitud física',
      'fr': 'Aptitude',
      'hi': 'स्वास्थ्य',
      'ja': 'フィットネス',
      'ro': 'Fitness',
    },
    'z5eid5sv': {
      'en': 'Select a Tag',
      'es': 'Seleccione una etiqueta',
      'fr': 'Sélectionnez une balise',
      'hi': 'एक टैग चुनें',
      'ja': 'タグを選択してください',
      'ro': 'Selectați o etichetă',
    },
    '0o56ybrt': {
      'en': 'Add Image',
      'es': 'Añadir imagen',
      'fr': 'Ajouter une image',
      'hi': 'छवि जोड़ें',
      'ja': '画像を追加',
      'ro': 'Adauga imagine',
    },
  },
  // image_details
  {
    'xb91bsxc': {
      'en': 'Title',
      'es': 'Título',
      'fr': 'Titre',
      'hi': 'शीर्षक',
      'ja': '題名',
      'ro': 'Titlu',
    },
    'jm710wn9': {
      'en': 'Mint This Image',
      'es': 'Menta esta imagen',
      'fr': 'Mentir cette image',
      'hi': 'मिंट दिस इमेज',
      'ja': 'この画像をミント',
      'ro': 'Mint această imagine',
    },
  },
  // profile
  {
    'zo3z0hzr': {
      'en': 'Account Settings',
      'es': 'Configuraciones de la cuenta',
      'fr': 'Paramètres du compte',
      'hi': 'अकाउंट सेटिंग',
      'ja': 'アカウント設定',
      'ro': 'Setările contului',
    },
    'iv8odjr8': {
      'en': 'Edit Profile',
      'es': 'Editar perfil',
      'fr': 'Editer le profil',
      'hi': 'प्रोफ़ाइल संपादित करें',
      'ja': 'プロファイル編集',
      'ro': 'Editează profilul',
    },
    'rkp94nvg': {
      'en': 'Order History',
      'es': 'Historial de pedidos',
      'fr': 'Historique des commandes',
      'hi': 'आदेश इतिहास',
      'ja': '注文履歴',
      'ro': 'Istoric comenzi',
    },
    '5ahstnmb': {
      'en': 'Settings',
      'es': 'Ajustes',
      'fr': 'Réglages',
      'hi': 'समायोजन',
      'ja': '設定',
      'ro': 'Setări',
    },
    '08jiwnwu': {
      'en': 'Notifications',
      'es': 'Notificaciones',
      'fr': 'Avis',
      'hi': 'सूचनाएं',
      'ja': '通知',
      'ro': 'Notificări',
    },
    'uv6a3b0u': {
      'en': 'Change Password',
      'es': 'Cambia la contraseña',
      'fr': 'Changer le mot de passe',
      'hi': 'पासवर्ड बदलें',
      'ja': 'パスワードを変更する',
      'ro': 'Schimbaţi parola',
    },
    'tnvl2w1b': {
      'en': 'Logout',
      'es': 'Cerrar sesión',
      'fr': 'Se déconnecter',
      'hi': 'लॉग आउट',
      'ja': 'ログアウト',
      'ro': 'Deconectare',
    },
    'rxsskr1h': {
      'en': 'My Profile',
      'es': 'Mi perfil',
      'fr': 'Mon profil',
      'hi': 'मेरी प्रोफाइल',
      'ja': '私のプロフィール',
      'ro': 'Profilul meu',
    },
  },
  // gallery
  {
    'h4ytfpny': {
      'en': 'My Images',
      'es': 'Mis Imágenes',
      'fr': 'Mes photos',
      'hi': 'मेरी छवियां',
      'ja': '私の画像',
      'ro': 'Imaginile mele',
    },
    'yw0opxuw': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    '0f249y6h': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'sm9frw0y': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'ah6hzirx': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'bagwo8sg': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'ajxoawky': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'gi1xbnsl': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    '5locvm1a': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    '6d9bs74r': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    '0evj07aa': {
      'en': 'Category Name',
      'es': 'nombre de la categoría',
      'fr': 'Nom de catégorie',
      'hi': 'श्रेणी नाम',
      'ja': '種別名',
      'ro': 'Numele categoriei',
    },
    'ls0esmbo': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
  },
  // filtered_list
  {
    '7p88eu90': {
      'en': 'Air Jordan XXXVI',
      'es': 'Air Jordan XXVI',
      'fr': 'Air Jordan XXXVI',
      'hi': 'एयर जॉर्डन XXXVI',
      'ja': 'エアジョーダンXXXVI',
      'ro': 'Air Jordan XXXVI',
    },
    'n9mz1ttw': {
      'en': '\$185.00',
      'es': '\$185.00',
      'fr': '185,00 \$',
      'hi': '\$185.00',
      'ja': '\$ 185.00',
      'ro': '185,00 USD',
    },
    'yyxzmxjh': {
      'en': 'Produced by Nike',
      'es': 'Producido por Niké',
      'fr': 'Produit par Nike',
      'hi': 'Nike . की बनाई फ़िल्में-टीवी शो',
      'ja': 'ナイキプロデュース',
      'ro': 'Produs de Nike',
    },
    'chvyb8j6': {
      'en': 'Lebron 19',
      'es': 'Lebrón 19',
      'fr': 'Lebron 19',
      'hi': 'लेब्रोन 19',
      'ja': 'レブロン19',
      'ro': 'Lebron 19',
    },
    '7euz6n4e': {
      'en': '\$200.00',
      'es': '\$200.00',
      'fr': '200,00 \$',
      'hi': '\$200.00',
      'ja': '\$ 200.00',
      'ro': '200,00 USD',
    },
    'nepvnxci': {
      'en': 'Produced by Nike',
      'es': 'Producido por Niké',
      'fr': 'Produit par Nike',
      'hi': 'Nike . की बनाई फ़िल्में-टीवी शो',
      'ja': 'ナイキプロデュース',
      'ro': 'Produs de Nike',
    },
    'nlhp4lvh': {
      'en': 'Products',
      'es': 'productos',
      'fr': 'Des produits',
      'hi': 'उत्पादों',
      'ja': '製品',
      'ro': 'Produse',
    },
  },
  // create_profile
  {
    'zagop9us': {
      'en': 'Change Photo',
      'es': 'Cambiar foto',
      'fr': 'Changer la photo',
      'hi': 'तस्वीर बदलिये',
      'ja': '写真を変更する',
      'ro': 'Schimbare fotografie',
    },
    'lxyesg45': {
      'en': 'Your Name',
      'es': 'Su nombre',
      'fr': 'votre nom',
      'hi': 'तुम्हारा  नाम',
      'ja': 'あなたの名前',
      'ro': 'Numele dumneavoastră',
    },
    'e0nyhw05': {
      'en': 'Email Address',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'ईमेल पता',
      'ja': '電子メールアドレス',
      'ro': 'Adresa de e-mail',
    },
    'qo1a3i8y': {
      'en': 'Save Changes',
      'es': 'Guardar cambios',
      'fr': 'Sauvegarder les modifications',
      'hi': 'परिवर्तनों को सुरक्षित करें',
      'ja': '変更内容を保存',
      'ro': 'Salvează modificările',
    },
    'd3nki2e5': {
      'en': 'Create Profile',
      'es': 'Crear perfil',
      'fr': 'Créer un profil',
      'hi': 'प्रोफ़ाइल बनाने',
      'ja': 'プロフィール作成',
      'ro': 'Creeaza un profil',
    },
  },
  // view_all
  {
    'gfnne6mq': {
      'en': 'Fitness',
      'es': 'Aptitud física',
      'fr': 'Aptitude',
      'hi': 'स्वास्थ्य',
      'ja': 'フィットネス',
      'ro': 'Fitness',
    },
    'i14o5fou': {
      'en': 'Title Will Go Here',
      'es': 'El título irá aquí',
      'fr': 'Le titre ira ici',
      'hi': 'शीर्षक यहाँ जाएगा',
      'ja': 'タイトルはここにあります',
      'ro': 'Titlul va merge aici',
    },
    'ahrhx0uy': {
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'hi': 'नाम',
      'ja': '名前',
      'ro': 'Nume',
    },
    'qfj4enl3': {
      'en': 'Fitness',
      'es': 'Aptitud física',
      'fr': 'Aptitude',
      'hi': 'स्वास्थ्य',
      'ja': 'フィットネス',
      'ro': 'Fitness',
    },
    'q3inqq28': {
      'en': 'Title Will Go Here',
      'es': 'El título irá aquí',
      'fr': 'Le titre ira ici',
      'hi': 'शीर्षक यहाँ जाएगा',
      'ja': 'タイトルはここにあります',
      'ro': 'Titlul va merge aici',
    },
    'ktph72qg': {
      'en': 'Name',
      'es': 'Nombre',
      'fr': 'Nom',
      'hi': 'नाम',
      'ja': '名前',
      'ro': 'Nume',
    },
  },
  // select_wallet
  {
    'vvvme32t': {
      'en': 'Select Wallet to Mint With',
      'es': 'Seleccione Monedero para acuñar con',
      'fr': 'Sélectionnez le portefeuille avec lequel frapper',
      'hi': 'टकसाल के साथ वॉलेट का चयन करें',
      'ja': 'ミントするウォレットを選択',
      'ro': 'Selectați Portofel cu care să moneți',
    },
    '0vbn1js5': {
      'en': 'Subtitle for the needs of description',
      'es': 'Subtítulo para las necesidades de descripción.',
      'fr': 'Sous-titre pour les besoins de la description',
      'hi': 'विवरण की आवश्यकता के लिए उपशीर्षक',
      'ja': '説明の必要性のための字幕',
      'ro': 'Subtitrare pentru nevoile de descriere',
    },
    'y77dn71t': {
      'en': 'Wallet Name',
      'es': 'Nombre de la billetera',
      'fr': 'Nom du portefeuille',
      'hi': 'वॉलेट का नाम',
      'ja': 'ウォレット名',
      'ro': 'Numele portofelului',
    },
    'ag3dxfw6': {
      'en': 'Wallet Name',
      'es': 'Nombre de la billetera',
      'fr': 'Nom du portefeuille',
      'hi': 'वॉलेट का नाम',
      'ja': 'ウォレット名',
      'ro': 'Numele portofelului',
    },
    '80fywaiw': {
      'en': 'Wallet Name',
      'es': 'Nombre de la billetera',
      'fr': 'Nom du portefeuille',
      'hi': 'वॉलेट का नाम',
      'ja': 'ウォレット名',
      'ro': 'Numele portofelului',
    },
    'vg4txoec': {
      'en': 'Wallet Name',
      'es': 'Nombre de la billetera',
      'fr': 'Nom du portefeuille',
      'hi': 'वॉलेट का नाम',
      'ja': 'ウォレット名',
      'ro': 'Numele portofelului',
    },
  },
  // side_nav
  {
    'gij00pdz': {
      'en': 'Home',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'ja': '家',
      'ro': 'Acasă',
    },
    'unqnq43g': {
      'en': 'My Images',
      'es': 'Mis Imágenes',
      'fr': 'Mes photos',
      'hi': 'मेरी छवियां',
      'ja': '私の画像',
      'ro': 'Imaginile mele',
    },
    'b1ga56xm': {
      'en': 'Wallet',
      'es': 'Cartera',
      'fr': 'Porte monnaie',
      'hi': 'बटुआ',
      'ja': '財布',
      'ro': 'Portofel',
    },
    'onnv0g6e': {
      'en': 'Profile',
      'es': 'Perfil',
      'fr': 'Profil',
      'hi': 'प्रोफ़ाइल',
      'ja': 'プロフィール',
      'ro': 'Profil',
    },
  },
  // Miscellaneous
  {
    'tbp2x0cs': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '9gqod0s3': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'ak939j8r': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'ouq1epka': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'etrlxh5j': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'wmse70v8': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'joxdko4k': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '3zelzkh3': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'm0je7m28': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'th2t3fkv': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'fn7vrpot': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'lsfrxubu': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'v1mbqlmp': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'o7217nr3': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '5gfyfwn3': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'fohrnqzh': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '6pznnr4d': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'm1mn81ml': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'awlqjzpi': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    'xervdfaz': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '1hszujkv': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
    '441imbj7': {
      'en': '',
      'es': '',
      'fr': '',
      'hi': '',
      'ja': '',
      'ro': '',
    },
  },
].reduce((a, b) => a..addAll(b));
